apiVersion: v1
kind: Service
metadata:
  name: containerflow-service
spec:
  type: NodePort
  selector:
    app: containerflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
